# Generated by Django 5.2.5 on 2025-08-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('processing', '处理中'), ('shipped', '已发货'), ('delivered', '已送达'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='运费')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='优惠金额')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('shipping_name', models.CharField(max_length=100, verbose_name='收货人姓名')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('shipping_address', models.TextField(verbose_name='收货地址')),
                ('shipping_zip_code', models.CharField(blank=True, max_length=10, verbose_name='邮政编码')),
                ('note', models.TextField(blank=True, verbose_name='订单备注')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('product_sku', models.CharField(max_length=50, verbose_name='产品SKU')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('product_attributes', models.JSONField(blank=True, null=True, verbose_name='产品属性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank_card', '银行卡'), ('cash', '现金'), ('other', '其他')], max_length=20, verbose_name='支付方式')),
                ('payment_status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='支付状态')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='交易流水号')),
                ('third_party_id', models.CharField(blank=True, max_length=100, verbose_name='第三方交易号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company', models.CharField(blank=True, max_length=100, verbose_name='快递公司')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='快递单号')),
                ('shipping_status', models.CharField(choices=[('preparing', '准备中'), ('shipped', '已发货'), ('in_transit', '运输中'), ('delivered', '已送达'), ('returned', '已退回')], default='preparing', max_length=20, verbose_name='配送状态')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配送记录',
                'verbose_name_plural': '配送记录',
            },
        ),
        migrations.CreateModel(
            name='ShippingTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('description', models.TextField(verbose_name='描述')),
                ('timestamp', models.DateTimeField(verbose_name='时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '配送跟踪',
                'verbose_name_plural': '配送跟踪',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '收藏夹',
                'verbose_name_plural': '收藏夹',
            },
        ),
    ]
